# Generated by Django 4.2.2 on 2023-06-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='sum_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
