# Generated by Django 4.2.2 on 2023-06-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0003_alter_payment_sum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='jewelry/'),
        ),
    ]
