# Generated by Django 4.2.2 on 2023-06-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0007_remove_jewelry_id_jewelry_jewelry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='jewelry_id',
        ),
        migrations.AddField(
            model_name='jewelry',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
