# Generated by Django 4.2.2 on 2023-06-25 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0008_remove_jewelry_jewelry_id_jewelry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jewelry',
            name='id',
        ),
        migrations.AddField(
            model_name='jewelry',
            name='jewelry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
