# Generated by Django 4.2.2 on 2023-06-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0011_alter_jewelry_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(upload_to='jewelry/'),
        ),
    ]
