# Generated by Django 4.2.2 on 2023-06-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LuxeGems', '0012_alter_jewelry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
